CREATE OR REPLACE PACKAGE PKG_SM1V4HIER_CUST
IS
-- TERRI HIERARCHY --
PROCEDURE SP_GENERATE (VCODDIV IN VARCHAR2);
PROCEDURE SP_USERS_DELIVERY(VCODDIV IN VARCHAR2);
PROCEDURE SP_USERS_B2B(VCODDIV IN VARCHAR2);
PROCEDURE REMOVE_ROWS ;
PROCEDURE SP_USERS_B2C(VCODDIV IN VARCHAR2);
PROCEDURE SP_USERS_MERCH_AUDIT(VCODDIV IN VARCHAR2);

-- AREA HIERARCHY --
PROCEDURE SP_USERS_AREA(VCODDIV IN VARCHAR2);

END PKG_SM1V4HIER_CUST;
